### ISSUE TITLE
How to create dynamic variables?

### ISSUE THREAD

**Issue by littleironical** [Nishant2907/Godseye#15]
We are trying to create a variable everytime loop starts...
Is there any way to achive this?
Because of this, we are unable to compare face encodings properly(in videoCode[test2]).

Check this:
https://github.com/Nishant2907/Godseye/blob/main/videoCode%5Btest2%5D.py

**Comment by Nishant2907** [comment]
Still working on this, have few doubts. But i think that using a variable based loop may work like:
`for encode in allName:`
`    encode = face_recognition.face_encodings(img)`
`     allEncode.append(encode)`

**Comment by littleironical** [comment]
I tried to do this but it's only putting the encodings in `allEncode` 
Not creating any **variable** in that.

**Comment by littleironical** [comment]
I solved this issue,
The probelem was not with creating variables.
I'm creating a pull request, do check and merge it

**Comment by Nishant2907** [comment]
We got the solution, closing the issue.
