### ISSUE TITLE
Problem with PR #17

### ISSUE THREAD

**Issue by littleironical** [Nishant2907/Godseye#18]
After Pull Request #17 , our code is not able to recognize multiple faces in one frame.
**I have removed a for loop in that code, and changed some variable names**

**Comment by Nishant2907** [comment]
I think the for loop functions to recognize multiple faces at a same instance, So removing the for loop made the program, recognize a single face at a single instance .

**Comment by littleironical** [comment]
Yeah, we have to use loop

**Comment by littleironical** [comment]
Check PR #19

**Comment by Nishant2907** [comment]
Solved the issue, by again adding the for loop.
