### ISSUE TITLE
Adding content in database

### ISSUE THREAD

**Issue by Nishant2907** [Nishant2907/Godseye#2]
1. Taking the project to a big scale (attendance system), we have to upload many pictures of people of the organization (**manually, which is not preferred by us**)
2. As we are going to take data of many people from an organization (minimum 100), should we create that number of objects also?
3. This will increase the complexity and length of the code.

**Comment by littleironical** [comment]
When we take the data to 100 people, we don't need to create 100 objects.
We just need to change the path of the image.

**Comment by littleironical** [comment]
We can use OS library for that to get the path of all images

**Comment by Nishant2907** [comment]
We can try using a list instead, where all the names will be already feeded(easily) and putting the encoding object in for loop(instead of making 100 objects).

**Comment by littleironical** [comment]
OS library does that only, it shows the path of the image(in our case) in list format.

**Comment by littleironical** [comment]
I've created a pull request #6 ... Do check this out.

**Comment by Nishant2907** [comment]
Checked the pull request and have merged it. The issue has been solved now and is closed.
