### ISSUE TITLE
Issue with waitKey function

### ISSUE THREAD

**Issue by littleironical** [Nishant2907/Godseye#3]
When **cv2.waitKey(0)** is disabled, result(True/False) is showing but image is not showing,
But when **cv2.waitKey(0)** is enabled, result is not showing but image is showing.

See the code at:
https://github.com/Nishant2907/Godseye/blob/main/initialCode.py

**Comment by Nishant2907** [comment]
This should not happen as there is no dependencies between waitKey and Compare function.

**Comment by littleironical** [comment]
Exactly, that's what I'm thinking.

**Comment by littleironical** [comment]
After running the code several times, I observed a few points:
1. when I run the code, two images pop up but result don't show in the terminal
2. but when I close those images, I'm getting the result in the terminal

**Comment by HarshitRuwali** [comment]
Here you were calling the `cv2.imshow()` before the prediction. Call the function before showing the image.<br>
I have pushed a pull request #5. Check that out.

**Comment by littleironical** [comment]
@Nishant2907 Please merge the pull request #5 
@HarshitRuwali Yes, showing the result before showing the image solved this issue.
I think the issue was not related to `waitKey` function.
As python code executes line by line, maybe that's why the result was not showing while images were showing.

Closing this issue as we got the solution.
