### ISSUE TITLE
Text alignment in images

### ISSUE THREAD

**Issue by littleironical** [Nishant2907/Godseye#4]
We are using `cv2.putText` to add the name of the person in the image, but the text position is not proper

See the code:
[https://github.com/Nishant2907/Godseye/blob/main/initialCode.py](initialCode.py)
Line21: `cv2.putText(imgJohnny, "Johnny Depp", (100, 100), cv2.FONT_HERSHEY_SIMPLEX, 1.0, (0, 255, 0), 2)`

How to position the text just below the rectangle box?

**Comment by littleironical** [comment]
I am able to position the text but still there's a problem
See the picture below:

![cropped](https://user-images.githubusercontent.com/61787056/95012269-f1e0e780-0654-11eb-9ed9-f146dc75c232.jpg)

The text is overflowing the image, how can we fix that?

**Comment by Nishant2907** [comment]
Temporarily solved the issue by enlarging the frame size.
